### ISSUE TITLE
Frequency is not counted properly when only 'Values' are given with number of bins

### ISSUE THREAD

**Issue by hodossy** [Microsoft/powerbi-visuals-histogram#7]
I have noticed that when not specifying frequencies, the sum of all frequency does not equal with the count of all input data.

In the [official example](https://visuals.azureedge.net/app-store/Histogram.1.0.0.0.pbix) on the usage of this visualization it can be perfectly seen, that the sum of frequencies on the 'Students exam result' page does not equal with the count of all students.

```
Bins: [7,12], (12,17], (17,22], (22,27], (27,32], (32,37], (37,42], (42,47], (47,52], (52,57], (57,62], (62,67], (67,72], (72,77], (77,82], (82,87], (87,92], (92,97]
Correct:   [1, 1, 1, 1, 2, 3, 4, 3, 2, 9, 9, 8, 6, 5, 1, 1, 1, 2]
By Visual: [1, 1, 1, 1, 2, 2, 2, 2, 2, 4, 3, 5, 3, 3, 1, 1, 1, 2]
```

The sum is not even 60 in case of this visual. It seems that value on the border are skipped (in spite the fact the the border is closed) in some cases.

**Comment by mvgaliev** [comment]
It is expected behavior from Power BI because all grouping values become just one if they are the same, however you can easily add the same value as measure with Count aggregation. And it will work as you expect.

**Comment by hodossy** [comment]
Ah, I see, it works now. I may worth to update the official example to reflect this.
